version: '3'

services:
    backend:
        container_name: backend
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            -   'host.docker.internal:host-gateway'
        ports:
            -   '8080:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            -   '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - database

    database:
        container_name: pgsql_database
        image: postgres:14
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: laravel_db
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - sail

networks:
    sail:
        driver: bridge
